### ISSUE TITLE
Questions regarding the decoder

### ISSUE THREAD

**Issue by chester256** [zhmiao/OpenCompoundDomainAdaptation-OCDA#2]
Thanks for releasing the code. It seems that the paper forgets to mention how to train the decoder while in the [code](https://github.com/zhmiao/OpenCompoundDomainAdaptation-OCDA/blob/c0fa91de83ba0d7fd3f54194f9a51acec0bb2eba/source/algorithms/train_domain_factor_net.py#L110) the decoder is updated jointly with the domain encoder.

**Comment by zhmiao** [comment]
Hello @chester256 , thank you very much for asking. Actually in section 3.1, Algorithm 1, and 2, there is information about the decoder. It is not extensively discussed in the paper because we think this is 1) the space is limited in the main text and 2) the novelty for this part is limited compared to the other components. We will add more details of decoder training in the supplementary. Does that make sense?

**Comment by chester256** [comment]
Thanks a lot

**Comment by xiao-keeplearning** [comment]
@zhmiao Hi, where can I find supplementary material？
